### PR TITLE
Add another option to show time remaining

### PR DESCRIPTION
**Pull request by ZachGoldberg**
I love this extension!  I also like that it has an option to show a percentage in addition to watts, I'd also love it if it showed an estimated time remaining.  

As I post this the PR isn't done, I'm not sure when I'll get a chance to finish it, hopefully soon, opening a draft just incase somehow this falls by the way side for me and someone else can get it across the line at some point.

UPDATE: it works!
image

### CODE REVIEW

**Comment by wennaspeedy** [comment]
Hi, Zack.

There's a problem with this extension and that's why I stopped developing it for new versions of gnome.

The problem is lagging. Every time you refresh the panel, it does a little lag. It may not be obvious on every machine or configuration, but it happens.

It's probably better to develop a new and better component that works completely differently.

**Comment by ZachGoldberg** [comment]
Hiya!  Any chance you have any more info on the bug reports re: lagging?  Is it just the couple of comments on the gnome extensions page?  I'd be happy to look into and try and reproduce/fix that issue.  I'm using the extension on a Framework 13 AMD and there's no issues, though I can imagine there are perhaps certain circumstances or other hardware where maybe there are issues.

**Comment by Cyclopropinon** [comment]
doesn't create any lag on my side, despite having older Hardware (a Thinkpad T410).
Anyways, what about adding individual options to have the watts & percentages also displayed with decimals (like in this screenshot)
grafik

**Comment by ZachGoldberg** [comment]
Great idea!  I added an issue in the forked repo that I'm maintaining now for widget, feel free to add more detail there - https://github.com/ZachGoldberg/batt_consumption_wattmetter/issues/1

**Pull request closed without merging**
